if(NOT DEFINED ENV{EXPECTED_DLL})
    message(FATAL_ERROR "EXPECTED_DLL is not set")
endif()
set(dll "$ENV{EXPECTED_DLL}")
if(NOT EXISTS "${dll}")
    message(FATAL_ERROR "Plugin DLL does not exist: ${dll}")
endif()
file(SIZE "${dll}" dll_size)
if(dll_size LESS 30000)
    message(FATAL_ERROR "Plugin DLL is unexpectedly small: ${dll_size}")
endif()
message(STATUS "Plugin artifact exists: ${dll} (${dll_size} bytes)")
